### ISSUE TITLE
Incorrectly reports error for the last list item that contains a nested paragraph

### ISSUE THREAD

**Issue by amimas** [textlint-rule/textlint-rule-period-in-list-item#3]
I have some content like this:

```markdown
- list item 1

    A paragraph describing this list item 1.

- list item 2.

    A paragraph describing this list item.

- list item 3

    Another paragraph describing list item 3.

```

The above snippet gets rendered properly by my markdown tool. The paragraphs appear indented within each list item.

When applying this rule, it will correctly identify that "list item 2" should not have a period at the end. Once that's corrected, it will complain about the period at the end of the paragraph under list item 3. There's no issue with having period in the other paragraph. The rule seems to interpret the last paragraph under the last list item as a separate list item.

**Comment by donganzh** [comment]
@azu hi are you able to help out with this issue? Much appreciate!

**Comment by azu** [comment]
Sorry I couldn't notice this issue.
I've confirmed that it is a bug.

Currently, this rule treat follwing 


```
- list item 1

    A paragraph describing this list item 1.

```

as `"- list item 1\n\n    A paragraph describing this list item 1.\n"`.

**Comment by azu** [comment]
Fix this issue in https://github.com/textlint-rule/textlint-rule-period-in-list-item/releases/tag/0.3.1

**Comment by donganzh** [comment]
thank you for the update!

**Comment by amimas** [comment]
@azu - Thanks for looking into this bug. I don't think the fix is working properly. For example: if I try the sample posted above:

![image](https://user-images.githubusercontent.com/16211767/59608409-47e9ee80-90e3-11e9-8120-bc6dc503c2a1.png)

I'm getting the following error after upgrading the linter rule to `0.3.1`:

```text
  90:44  ✓ error  Should remove period mark(".") at end of list item  period-in-list-item
  94:42  ✓ error  Should remove period mark(".") at end of list item  period-in-list-item
  98:45  ✓ error  Should remove period mark(".") at end of list item  period-in-list-item
```

Looks like the linter rule is taking the paragraphs under each list items as part of the list item and reporting them as error because they have a period at the end.

**Comment by amimas** [comment]
can we reopen this issue, please?

**Comment by amimas** [comment]
@azu - Is there anything we can do to get this fixed? My colleague @donganzh can look into it further if you have any more comments for his PR https://github.com/textlint-rule/textlint-rule-period-in-list-item/pull/5

**Comment by azu** [comment]
Ah, I misunderstood it

if the config is

```
{
  "periodMark": "."
}
```

The text 

```
- list item 1

    A paragraph describing this list item 1

- list item 2

    A paragraph describing this list item 2

- list item 3

    A paragraph describing this list item 4
```

to be


```
- list item 1.

    A paragraph describing this list item 1

- list item 2.

    A paragraph describing this list item 2

- list item 3.

    A paragraph describing this list item 4
```

**Comment by azu** [comment]
https://github.com/textlint-rule/textlint-rule-period-in-list-item/releases
Please try it,.

**Comment by amimas** [comment]
Thanks for releasing this fix @azu and your help @donganzh 
I just tried it out and it worked great. What's even better is that the latest release (`0.3.2`) was able to find and report valid issues that weren't being reported by `0.3.0`
